thread = 2
logger = nil
harbor = 0
bootstrap = "snlua bootstrap"
start = "skyuv_benchmark_actor_ping_pong"

benchmark_warmup = "$SKYUV_BENCHMARK_WARMUP"
benchmark_duration = "$SKYUV_BENCHMARK_DURATION"
benchmark_iterations = "$SKYUV_BENCHMARK_ITERATIONS"

cpath = "./cservice/?.so"
lua_path = "./lualib/?.lua;./lualib/?/init.lua"
lua_cpath = "./luaclib/?.so"
luaservice = "./service/?.lua;./examples/?.lua"
lualoader = "./lualib/loader.lua"
