thread = 4
logger = nil
harbor = 0
start = "skyuv_tcp_events"
bootstrap = "snlua bootstrap"
luaservice = "./service/?.lua;./test/?.lua;./examples/?.lua"
lualoader = "./lualib/loader.lua"
lua_path = "./lualib/?.lua;./lualib/?/init.lua"
lua_cpath = "./luaclib/?.so"
cpath = "./cservice/?.so"
