thread = 2
logger = nil
harbor = 0
bootstrap = "snlua bootstrap"
start = "skyuv_benchmark_tcp_echo"

cpath = "./cservice/?.so"
lua_path = "./lualib/?.lua;./lualib/?/init.lua"
lua_cpath = "./luaclib/?.so"
luaservice = "./service/?.lua"
lualoader = "./lualib/loader.lua"

benchmark_message_size = "$SKYUV_BENCHMARK_MESSAGE_SIZE"
