thread = 2
logger = nil
harbor = 0
bootstrap = "snlua bootstrap"
start = "skyuv_client_socket"

cpath = "./cservice/?.so"
lua_path = "./lualib/?.lua;./lualib/?/init.lua"
lua_cpath = "./luaclib/?.so"
luaservice = "./service/?.lua"
lualoader = "./lualib/loader.lua"
